name: yarp-again
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest
  - pip
  - pyaml
  - ipython
  - ipykernel
  - rdkit
  - openbabel
  - scipy
  - pandoc
  - pip:
    - tabulate
    - sphinx-rtd-theme
    - sphinx-autoapi 
    - sphinx