name: yarp
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytest
  - pip
  - pyaml
  - ipython
  - ipykernel
  - rdkit
  - openbabel
  - numpy
  - scipy
  - pandoc
  - networkx
  - pip:
    - tabulate
    - sphinx-rtd-theme
    - sphinx-autoapi 
    - sphinx
    - pytest-mock
    - ase
    - h5py
