# Note that a bimolecular reaction is recommended to use .xyz or .mol file
# input reaction/reactant
input: /scratch/negishi/li1724/013125-yarp/yarp/pyTEST_Example/Class-Refinement-Example/reaction_xyz/

# output folder for yarp
scratch: /scratch/negishi/li1724/013125-yarp/yarp/pyTEST_Example/Class-Refinement-Example/

# the dictionary for result (reaction class)
reaction_data: 0.p

# Enumetation part
enumeration: False # define whether user uses enumeration or not
lewis_criteria: 1.0 # the criteria for accepting a product or not
ff: uff # the force field for locating initial product
n_break: 2 # indicate the elementary reaction (bnfn reaction)
form_all: False # if true, bnfm reaction will be applied. (forming all possible bonds. This matters for the atoms with unpaired electron. For example, oxygen.)

# Basic settings for low-level calculation
method: crest # the conformational sampling method. (option: crest/rdkit)
crest: crest # the cmd for CREST
xtb: xtb # the cmd for xTB
lot: gfn2 # the level of theory for xTB
n_conf: 10 # the number of conformers
strategy: 2 # the strategy for conf sampling (0: reactant side; 1: product side; 2: both sides)
nprocs: 24 # the processor for running low-level calculation
c_nprocs: 24 # the processor for running conf sampling
opt_level: normal # the optimization level
low_solvation: gbsa/DMSO # the low solvation model and solvent for xTB
solvent: DMSO
opt: False
pysis_wt: 3600 # the time for running pysis (in second)
crest_quick: False

# Basic setting for DFT calculations
package: ORCA # options: ORCA and Gaussian
dft_ppn: 24
dft_nprocs: 24 # the processor for running DFT
#dft_lot: wB97X D4 def2-TZVP # the functional and basis set for DFT # Zhao's note: D4 functional seems broken
# in long term, need to separate functional and basis set
functional: wB97X
basis_set: def2-TZVP # the functional and basis set for DFT
dispersion: False # only valid for Gaussian (if will apply GD3 dispersion correction)
dft_wt: 4 # the time for running DFT (in hours)
#partition: bsavoie # options: bsavoie or standby
partition: standby # options: bsavoie or standby
hess_recalc: 1 # work for ORCA
dft_irc: True # indicate whether IRC is applied
nconf_dft: 3
mem: 2 # in GB
skip_low_IRC: False
skip_low_TS: False
dft_njobs: 1
constrained_TS: False
select: network
charge: 0
multiplicity: 2
dielectric: 0.0
model_path:   /home/hsu205/classy-yarp/reaction/bin
gsm_inp:      /home/hsu205/classy-yarp/reaction/bin/inpfileq
backward_DE: False
dielectric: 0
#solvation:  False
dispersion: False
