# Note that a bimolecular reaction is recommended to use .xyz or .mol file
# Enumetation part
input: xyz_test # (1) The input folder with .xyz or .mol file (2) a text file with multiple smiles
scratch: /scratch/negishi/hsu205/classy-test # The output folder with reaction geometry for constructing reaction network.
n_break: 2 # Indicate the number of breaking bonds
form_all: False # Forming all possible bonds (matters for lone paired electrons (oxygen, sulfur, and other similar atoms)) (default: 0) 
lewis_criteria: 0.0 # the criteria to find the products
ff:            mmff94        # force field for driving the reaction coordinate           
crest: crest
lot: gfn1
crest_quick: False
xtb: xtb
method: crest
enumeration: True # if you only have reactant, you will need to do enumeration. Ohterwise, you need to provide reaction geometry.
n_conf: 3
strategy: 2
nprocs: 16
c_nprocs: 16
mem: 1
crest: crest
opt_level: vtight
crest_quick: False
low_solvation: False
opt: False
pysis_wt: 180
select: network
charge: 0
multiplicity: 1
model_path:   /home/hsu205/classy-yarp/reaction/bin
gsm_inp:      /home/hsu205/classy-yarp/reaction/bin/inpfileq
