import yaml
import pytest
from pathlib import Path
from yarp.initialize_yarp import initialize_from_dict

# Assuming your test yaml files are stored in a 'tests/data' directory
DATA_DIR = Path(__file__).parent / "../main_inputs"

def test_happy_path_initialization():
    """
    Test 1: enum_egat_llpath_llrefine.yaml
    Verifies that a full pipeline is parsed correctly and internal dependencies
    are mapped, resulting in 'pending' statuses for downstream tasks.
    """
    yaml_path = DATA_DIR / "enum_egat_llpath_llrefine.yaml"
    with open(yaml_path, 'r') as f:
        file_dict = yaml.safe_load(f)
        
    reactions, status_tracker = initialize_from_dict(file_dict)
    
    # Verify reaction generation
    assert len(reactions) == 2, "Expected exactly 2 reaction objects generated."
    
    # Extract the task list
    pipeline_tasks = status_tracker["pipeline_tasks"]
    
    # Check that all expected tasks were dynamically generated by the parser
    expected_tasks = [
        "egat.ml_predict", 
        "ll_path.reactant_conformer", 
        "ll_path.product_conformer", 
        "ll_path.gsm",
        "ll_refine.reactant_optimization",
        "ll_refine.product_optimization",
        "ll_refine.transition_state_optimization",
        "ll_refine.irc_validation"
    ]
    for task in expected_tasks:
        assert task in pipeline_tasks, f"Missing expected task: {task}"
        
    # Pick a random reaction hash to inspect its initial state
    rxn_hash = list(reactions.keys())[0]
    rxn_tasks = status_tracker["reactions"][rxn_hash]["tasks"]
    
    # The conformer steps have no dependencies, they should be ready immediately
    assert rxn_tasks["ll_path.reactant_conformer"]["status"] == "ready"
    assert rxn_tasks["ll_path.product_conformer"]["status"] == "ready"
    
    # GSM depends on the conformers, so it MUST be pending
    assert rxn_tasks["ll_path.gsm"]["status"] == "pending"

    # Reactant-Product OPT waits for conformers to be generated, so they are pending
    assert rxn_tasks["ll_refine.reactant_optimization"]["status"] == "pending"
    assert rxn_tasks["ll_refine.product_optimization"]["status"] == "pending"

    # TSOPT assumes no TS guess is available due to presence of gsm, so it is pending
    assert rxn_tasks["ll_refine.transition_state_optimization"]["status"] == "pending"

    # IRC Validation depends on TS optimization, so it MUST be pending
    assert rxn_tasks["ll_refine.irc_validation"]["status"] == "pending"


def test_missing_init_path_initialization():
    """
    Test 2: enum_egat_llrefine.yaml
    Verifies that when a prerequisite stage is missing, the DAG does not
    create execution dependencies, leaving tasks 'ready' to fail gracefully later.
    """
    yaml_path = DATA_DIR / "enum_egat_llrefine.yaml"
    with open(yaml_path, 'r') as f:
        file_dict = yaml.safe_load(f)
        
    reactions, status_tracker = initialize_from_dict(file_dict)
    
    # Verify reaction generation
    assert len(reactions) == 2, "Expected exactly 2 reaction objects generated."
    
    pipeline_tasks = status_tracker["pipeline_tasks"]
    
    # Ensure the init path tasks are completely absent
    assert "ll_path.gsm" not in pipeline_tasks
    
    # Inspect the state
    rxn_hash = list(reactions.keys())[0]
    rxn_tasks = status_tracker["reactions"][rxn_hash]["tasks"]
    
    # CRITICAL CHECK: Because ll_path was skipped, no task in the pipeline promises "ts_guess".
    # Therefore, ts_opt shouldn't have any internal pipeline dependencies holding it back.
    # It starts as "ready" and will fail the Calculator.has_prerequisites() check in progress_yarp.py!
    assert rxn_tasks["ll_refine.transition_state_optimization"]["status"] == "ready"

    # Similar story for the reactant/product optimization steps
    assert rxn_tasks["ll_refine.reactant_optimization"]["status"] == "ready"
    assert rxn_tasks["ll_refine.product_optimization"]["status"] == "ready"
    
    # However, IRC validation STILL depends on ts_opt because they are both within the ll_refine stage!
    assert rxn_tasks["ll_refine.irc_validation"]["status"] == "pending"