import yaml
import pickle
from pathlib import Path
from yarp.initialize_yarp import initialize_from_dict, initialize_yarp

def test_happy_path_initialization(enum_egat_llpath_llrefine):
    """
    Test 1: enum_egat_llpath_llrefine.yaml
    Verifies that a full pipeline is parsed correctly and internal dependencies
    are mapped, resulting in 'pending' statuses for downstream tasks.
    """
        
    reactions, status_tracker = initialize_from_dict(enum_egat_llpath_llrefine)
    
    # Verify reaction generation
    assert len(reactions) == 11, "Expected exactly 11 reaction objects generated."

    # Check that all expected global tasks were dynamically generated by the parser
    global_tasks = status_tracker["global_tasks"]
    expected_global_tasks = [
        "egat.ml_predict"
    ]
    for task in expected_global_tasks:
        assert task in global_tasks, f"Missing expected global task: {task}"

    # Check that all expected pipeline tasks were dynamically generated by the parser
    pipeline_tasks = status_tracker["pipeline_tasks"]
    expected_pipeline_tasks = [
        "ll_path.reactant_conformer",
        "ll_path.product_conformer",
        "ll_path.ts_guess",
        "ll_refine.reactant_optimization",
        "ll_refine.product_optimization",
        "ll_refine.transition_state_optimization",
        "ll_refine.irc_validation"
    ]
    for task in expected_pipeline_tasks:
        assert task in pipeline_tasks, f"Missing expected pipeline task: {task}"

    # Pick a random reaction hash to inspect its initial state
    rxn_hash = list(reactions.keys())[0]
    rxn_tasks = status_tracker["reactions"][rxn_hash]["tasks"]
    
    # The conformer steps wait for EGAT barriers, so they are pending
    assert rxn_tasks["ll_path.reactant_conformer"]["status"] == "pending"
    assert rxn_tasks["ll_path.product_conformer"]["status"] == "pending"
    
    # GSM depends on the conformers, so it MUST be pending
    assert rxn_tasks["ll_path.ts_guess"]["status"] == "pending"

    # Reactant-Product OPT waits for conformers to be generated, so they are pending
    assert rxn_tasks["ll_refine.reactant_optimization"]["status"] == "pending"
    assert rxn_tasks["ll_refine.product_optimization"]["status"] == "pending"

    # TSOPT assumes no TS guess is available due to presence of gsm, so it is pending
    assert rxn_tasks["ll_refine.transition_state_optimization"]["status"] == "pending"

    # IRC Validation depends on TS optimization, so it MUST be pending
    assert rxn_tasks["ll_refine.irc_validation"]["status"] == "pending"


def test_enum_minimal(enum_min_options):
    input_dict = enum_min_options
    initialize_yarp(input_dict)

    output_str = input_dict['initialize']['output']
    output = Path(output_str)
    assert output.exists(), "Output pickle file was not created"

    with open(output_str, "rb") as f:
        saved_reactions = pickle.load(f)
    
    assert len(saved_reactions) == 11

def test_enum_full(enum_full_options):
    input_dict = enum_full_options
    initialize_yarp(input_dict)

    output_str = input_dict['initialize']['output']
    output = Path(output_str)
    assert output.exists(), "Output pickle file was not created"

    with open(output_str, "rb") as f:
        saved_reactions = pickle.load(f)

    assert len(saved_reactions) == 2
