import yaml
import pickle
from copy import deepcopy
from pathlib import Path
from yarp.initialize_yarp import initialize_from_dict, initialize_yarp, save_state
from yarp.reaction.reaction import reaction
from yarp.yarpecule.hashes import reaction_hash


def assert_current_reaction_hash_keys(reactions):
    """Assert serialized dictionary keys come from the current hash function."""
    assert set(reactions) == {
        str(reaction_hash(rxn)) for rxn in reactions.values()
    }

def test_happy_path_initialization(enum_egat_llpath_llrefine):
    """
    Test 1: enum_egat_llpath_llrefine.yaml
    Verifies that a full pipeline is parsed correctly and internal dependencies
    are mapped, resulting in 'pending' statuses for downstream tasks.
    """
        
    reactions, status_tracker = initialize_from_dict(enum_egat_llpath_llrefine)
    
    # Verify reaction generation
    assert len(reactions) == 13, "Expected 13 canonical reaction objects."
    assert_current_reaction_hash_keys(reactions)

    # Check that all expected global tasks were dynamically generated by the parser
    global_tasks = status_tracker["global_tasks"]
    expected_global_tasks = [
        "egat.ml_predict"
    ]
    for task in expected_global_tasks:
        assert task in global_tasks, f"Missing expected global task: {task}"

    # Check that all expected pipeline tasks were dynamically generated by the
    # parser. Compared as a set, not a subset: a task appearing that nobody
    # expected is as much of a change as one going missing.
    pipeline_tasks = status_tracker["pipeline_tasks"]
    expected_pipeline_tasks = [
        "ll_path.reactant_pre_opt",
        "ll_path.product_pre_opt",
        "ll_path.reactant_conformer",
        "ll_path.product_conformer",
        "ll_path.ts_guess",
        "ll_refine.reactant_optimization",
        "ll_refine.product_optimization",
        "ll_refine.transition_state_optimization",
        "ll_refine.irc_validation"
    ]
    assert set(pipeline_tasks) == set(expected_pipeline_tasks)

    # Pick a random reaction hash to inspect its initial state
    rxn_hash = list(reactions.keys())[0]
    rxn_tasks = status_tracker["reactions"][rxn_hash]["tasks"]

    # The xTB pre-optimization runs ahead of conformer generation; its reactant
    # leg waits on EGAT and its product leg waits on the reactant leg.
    assert rxn_tasks["ll_path.reactant_pre_opt"]["status"] == "pending"
    assert rxn_tasks["ll_path.product_pre_opt"]["status"] == "pending"

    # The conformer steps now wait for the pre-optimization, so they are pending
    assert rxn_tasks["ll_path.reactant_conformer"]["status"] == "pending"
    assert rxn_tasks["ll_path.product_conformer"]["status"] == "pending"
    
    # GSM depends on the conformers, so it MUST be pending
    assert rxn_tasks["ll_path.ts_guess"]["status"] == "pending"

    # Reactant-Product OPT waits for conformers to be generated, so they are pending
    assert rxn_tasks["ll_refine.reactant_optimization"]["status"] == "pending"
    assert rxn_tasks["ll_refine.product_optimization"]["status"] == "pending"

    # TSOPT assumes no TS guess is available due to presence of gsm, so it is pending
    assert rxn_tasks["ll_refine.transition_state_optimization"]["status"] == "pending"

    # IRC Validation depends on TS optimization, so it MUST be pending
    assert rxn_tasks["ll_refine.irc_validation"]["status"] == "pending"


def test_enum_minimal(enum_min_options):
    input_dict = enum_min_options
    initialize_yarp(input_dict)

    output_str = input_dict['initialize']['output']
    output = Path(output_str)
    assert output.exists(), "Output pickle file was not created"

    with open(output_str, "rb") as f:
        saved_reactions = pickle.load(f)
    
    assert len(saved_reactions) == 13
    assert_current_reaction_hash_keys(saved_reactions)

def test_enum_full(enum_full_options):
    input_dict = enum_full_options
    initialize_yarp(input_dict)

    output_str = input_dict['initialize']['output']
    output = Path(output_str)
    assert output.exists(), "Output pickle file was not created"

    with open(output_str, "rb") as f:
        saved_reactions = pickle.load(f)

    assert len(saved_reactions) == 2
    assert_current_reaction_hash_keys(saved_reactions)

def test_enum_d2_pkl(enum_d2_pkl):
    input_dict = enum_d2_pkl
    initialize_yarp(input_dict)

    output_str = input_dict['initialize']['output']
    output = Path(output_str)
    assert output.exists(), "Output pickle file was not created"

    with open(output_str, "rb") as f:
        saved_reactions = pickle.load(f)

    # Four forward/reverse pairs collapse to one nondirectional reaction each.
    assert len(saved_reactions) == 21
    assert_current_reaction_hash_keys(saved_reactions)


def test_next_depth_keeps_original_reactions(enum_d2_pkl, tmp_path, capsys):
    """Saved string keys and mixed keys must retain the first forward record."""
    first, tracker = initialize_from_dict(enum_d2_pkl)
    metadata_fields = (
        "barrier", "reverse_barrier", "heat_of_rxn", "dg_rxn",
        "outcome_label", "network_meta",
    )
    for index, rxn in enumerate(first.values()):
        for field in metadata_fields:
            getattr(rxn, field)["original_index"] = index
    save_state(tmp_path, first, tracker)
    capsys.readouterr()

    next_input = deepcopy(enum_d2_pkl)
    next_input["initialize"]["initial_structure"]["source"] = tracker["reaction_output_file"]
    second, _ = initialize_from_dict(next_input)
    assert "Skipping duplicate reaction hash" in capsys.readouterr().out
    assert set(first) <= set(second)
    assert len(second) > len(first)
    for key, original in first.items():
        retained = second[key]
        assert retained.id == original.id
        assert retained.reactant.graph.atom_info == original.reactant.graph.atom_info
        assert retained.product.graph.atom_info == original.product.graph.atom_info
        for field in metadata_fields:
            assert getattr(retained, field) == getattr(original, field)

    first_key = next(
        key for key, rxn in first.items()
        if rxn.reactant.inchi != rxn.product.inchi
    )
    reverse = reaction(first[first_key].product.graph, first[first_key].reactant.graph)
    reverse.network_meta["original_index"] = "later duplicate"
    mixed = dict(first)
    mixed[float(first_key)] = reverse
    mixed_path = tmp_path / "mixed_reactions.pkl"
    with mixed_path.open("wb") as stream:
        pickle.dump(mixed, stream)
    next_input["initialize"]["initial_structure"]["source"] = str(mixed_path)
    mixed_output, _ = initialize_from_dict(next_input)
    assert "Skipping duplicate reaction hash" in capsys.readouterr().out
    assert mixed_output[first_key].id == first[first_key].id
    for field in metadata_fields:
        assert getattr(mixed_output[first_key], field) == getattr(first[first_key], field)

# ERM: There are some known bugs with the generation of XYZs/SMILES that are probably causing
# the observed errors for these test cases
# def test_enum_d2_smi(enum_d2_smi):
#     input_dict = enum_d2_smi
#     initialize_yarp(input_dict)

#     output_str = input_dict['initialize']['output']
#     output = Path(output_str)
#     assert output.exists(), "Output pickle file was not created"

#     with open(output_str, "rb") as f:
#         saved_reactions = pickle.load(f)

#     assert len(saved_reactions) == 28

# def test_enum_d2_xyz_dir(enum_d2_xyz_dir):
#     input_dict = enum_d2_xyz_dir
#     initialize_yarp(input_dict)

#     output_str = input_dict['initialize']['output']
#     output = Path(output_str)
#     assert output.exists(), "Output pickle file was not created"

#     with open(output_str, "rb") as f:
#         saved_reactions = pickle.load(f)

#     assert len(saved_reactions) == 28
