"""
Testing suite for the network class
"""
from yarp.network.network import network
from yarp.yarpecule.yarpecule import yarpecule as ypcule
import pytest
from networkx.exception import NodeNotFound


def test_khp2pp22_soergel_beam2_cyc3(khp2pp22_soergel_beam2_cyc3):
    """
    Test basic network class routines for network generated by product blinders
    """
    crn = network(khp2pp22_soergel_beam2_cyc3, dG_lot='egat_rgd1')
    start = ypcule('O=CCOO')
    target = ypcule('OC1CCOO1')

    assert crn.n_species == 48
    assert crn.n_rxns == 78
    assert crn.n_considered_rxns == 4

    terminals = crn.get_terminal_species()
    assert len(terminals) == 43
    cyc3_terminals = []
    for mol in terminals:
        if crn.calc_min_dist(start=start, end=mol) == 2:
            cyc3_terminals.append(mol)
    assert len(cyc3_terminals) == 13

    with pytest.raises(NodeNotFound, match=f"Target Sp_{target.hash} is not in G"):
        crn.calc_min_dist(start=start, end=target)
    