# Note that a bimolecular reaction is recommended to use .xyz or .mol file
# Enumetation part
#input:  /scratch/negishi/li1724/110124-YARP-Github/110824-yarp/classy-yarp/pyTEST_Example//reaction_xyz/DA.xyz # (1) The input folder with .xyz or .mol file (2) a text file with multiple smiles
input:  reaction_xyz # (1) The input folder with .xyz or .mol file (2) a text file with multiple smiles
scratch: /scratch/negishi/li1724/041625-yarp-branch/yarp/pyTEST_Example/Class-main_dft-Example/Half-Done-TEST/RESULT/
# The output folder with reaction geometry for constructing reaction network.
reaction_data: DA.p
#n_break: 2 # Indicate the number of breaking bonds
n_break: 1 # Indicate the number of breaking bonds
form_all: False # Forming all possible bonds (matters for lone paired electrons (oxygen, sulfur, and other similar atoms)) (default: 0) 
#n_form: 2
n_form: 1
lewis_criteria: 1000.0 # the criteria to find the products
ff:            uff        # force field for driving the reaction coordinate           
lot: gfn2
crest_quick: False
method: crest
enumeration: False # if you only have reactant, you will need to do enumeration. Ohterwise, you need to provide reaction geometry.

#GSM_Calculator: GSM
JointOptimizationMethod: xTB
String_use_only_middle_images: True # exclude first and last images when doing GSM through pysis
opt: True
#opt_reactant_aswell: False
Metal_Constraints: False
JointOptimizationUseActualBondLengthAsReference: True
TSOPT_RemoveDuplicateTS: False
JointOptimizationForceConstant: 0.1

n_conf: 15
nconf_dft: 15
strategy: 2
nprocs: 24
c_nprocs: 12
#mem: 3.6 # in GB
mem: 2 # in GB
#xtb: /home/li1724/.conda/envs/2022.10-py39/IOP/bin/xtb
xtb: xtb
crest: /home/li1724/.conda/envs/2022.10-py39/copy-classy-yarp/bin/crest
opt_level: vtight
crest_quick: False
pysis_wt: 14400
select: network
charge: 0
multiplicity: 1
skip_low_IRC: False
skip_low_TS:  False
constrained_TS: False
model_path:   /home/li1724/Classy-YARP-Codes_012525/GitClone/bin
gsm_inp:      /home/li1724/Classy-YARP-Codes_012525/GitClone/bin/inpfileq

rp_opt: False # skip the reactant/product DFT calculations
package: ORCA # Gaussian
dft_irc_package: ORCA
email_address: zhaoli2023@u.northwestern.edu
dft_nprocs: 24  # Number of cores used by ORCA
functional: PBE 
basis_set: def2-SVP
dft_wt: 4
dft_ppn: 24    # the number of ppn used in the submission (SLURM File)
#dft_ppn: 24    # the number of ppn used in the submission (SLURM File)
partition: standby
dft_njobs: 1
hess_recalc: 1
dft_mix_basis: True
dft_mix_lot: Rh, def2-TZVP, H, STO-3G    # level of theory for special atoms/elements
dft_mix_firstlayer: True    # add mix lot for 1st layer of metal
dft_mix_firstlayer_lot: def2-TZVP # basis for the 1st layer atoms
dft_fulltz_level_correction: False # whether to recalculate single point energy after the OPT/TSOPT calculation using a less expensive basis set
dft_irc: True
backward_DE: True
dielectric: 0
solvation: CPCM/DMSO
dispersion: False

verbose: False
dry_run: True

dft_run_ts: True
dft_run_rp: True

irc_partition: bsavoie
irc_wt: 96
separate_product: False
separate_reactant: False
DFT_Folder: OPT_DFT
selected_conformers: 30, 34, 35
