initialize:
  enumerate: true
  mode: concerted
  initial species: /groups/bsavoie2/tburton2/yarp_networks/Network_Gen_v01/outputs_group5/C1_CC_CC_C1_d6234cfb/C1_CC_CC_C1__20260304_142933__b2f2_d1.pkl.
  output: /groups/bsavoie2/tburton2/yarp_networks/Network_Gen_v01/d2_out.pkl
  bonds to break: 2
  bonds to form: 2
  separate products: null
  enumeration filters:
    lewis score: 0
    formal charge: 3.0
    discard strained rings: false
    barrier cutoff: 120.0
    barrier source: egat
stages:
- egat
egat:
  method: ml_predict
  model: egat_pretrain
