initialize:
  enumerate: True
  initial species: '[O:7]=[CH:7]CCOO'
  output: dev_failure_duplicate_map.pkl
  mode: concerted
  bonds to break: 2
  bonds to form: 2
  enumeration filters:
    lewis score: 0.0
    formal charge: 2.0
    discard strained rings: False

stages:
  - egat

egat:
  method: ml_predict
  model: egat_pretrain
