initialize:
  enumerate: True
  initial species: '[18O]=CCCOO'
  output: dev_smoke_isotope.pkl
  mode: concerted
  bonds to break: 2
  bonds to form: 2
  reactive atoms: [0, 1, 2, 3, 4, 5]
  enumeration filters:
    lewis score: 0.0
    formal charge: 2.0
    discard strained rings: False

stages:
  - egat

egat:
  method: ml_predict
  model: egat_pretrain
