initialize:
  enumerate: True
  initial species: '[O:30]=[CH:10][CH2][CH2:22]O[O:50]'
  output: dev_failure_sparse_map_egat.pkl
  mode: concerted
  bonds to break: 2
  bonds to form: 2
  enumeration filters:
    lewis score: 0.0
    formal charge: 2.0
    discard strained rings: False

stages:
  - egat

egat:
  method: ml_predict
  model: egat_pretrain
