"""
Miscellaneous utility functions for the yarp package.
(I hate this, but we'll use this for now - ERM)
"""

import numpy as np
from yarp.yarpecule.lewis.be_mat import return_formals


def prepare_list(x):
    """
    Many of the functions in the yarp library expect a list of objects, although in many use cases the user may
    only supply a single object. It is awkward behavior to ask the user to supply a single object inside of a list
    so this function handles performs the list wrapping for the user when functions expect a list and instead
    are passed a single instance of the object. 

    Parameters
    ----------
    x: list or object
       In a typical use case, this is an input to a function or method in the yarp package. 

    Returns
    -------
    x: list
       The purpose of this function is to ensure that the supplied object is wrapped in a list if it 
       is not already a list.
    """
    if isinstance(x, (tuple, list)):
        return x
    else:
        return [x]


def merge_arrays(list_of_arrays):
    """
    This function takes a list of arrays and concatenates them along the diagonal of a new array, 
    such that each array in the original list occupies a subblock of the new array and the off-diagonal
    elements where the sub-blocks overlap are zero. For example, suppose the input to this function is 
    a list of three arrays. The first array in `list_of_arrays` is of size 2x2, the second array is of
    size 3x3, and the third array is of size 4x4. `merge_arrays` will return a new array of size 9x9 
    (i.e., 2+3+4) with the elements of the 2x2 array in the [0,0],[0,1],[1,0], and [1,1] positions, 
    the elements of the 3x3 array in postitions [2,2],[2,3],[2,4],[3,2],[3,3],[3,4], etc.  

    Parameters
    ----------
    list_of_arrays: list of arrays
                    A list of square numpy arrays.

    Returns
    -------
    merged_array: array
                  The merged array consisting of the sub-arrays concatenated along the diagonal blocks.
    """

    # Handle singular use-case
    list_of_arrays = prepare_list(list_of_arrays)

    # Get the dimensions of each input array
    dimensions = [arr.shape[0] for arr in list_of_arrays]

    # Calculate the dimensions of the merged array
    merged_dim = sum(dimensions)

    # Initialize the merged array with zeros
    merged_array = np.zeros((merged_dim, merged_dim),
                            dtype=list_of_arrays[0].dtype)

    # Iterate through each input array and copy its elements to the merged array
    row_offset = 0
    for arr in list_of_arrays:
        size = arr.shape[0]
        merged_array[row_offset:row_offset + size,
                     row_offset:row_offset + size] = arr
        row_offset += size

    return merged_array


def mol_write_yp(file, elements, geo, bond_mat, adj_mat, append_opt=False):
    """
    Write a MOL file to disk from a yarpecule object.
    Or rather, from attributes passed in from a yarpecule object.
    We don't take kindly to attempts to update the core attributes of a class
    when we're not a class function.

    Parameters:
    -----------
    name : str
        Name of file to be generated

    elements : list of str
        Elements of molecule

    geo : numpy.ndarray
        3D cartesian coordinates of atoms in molecule

    bond_mat : numpy.ndarray
        bond electron matrix of the molecule

    adj_mat : numpy.ndarray
        adjacency matrix of the molecule

    append_opt : bool (default = False)
        If true, MOL file will be generated in append mode.
        If false, MOL file will be generated in write mode.
    """

    # Consistency check
    if len(elements) >= 1000:
        print("ERROR in mol_write: the V2000 format can only accomodate up to 1000 atoms per molecule.")
        return
    mol_dict = {3: 1, 2: 2, 1: 3, -1: 5, -2: 6, -3: 7, 0: 0}
    # Check for append vs overwrite condition
    if append_opt == True:
        open_cond = 'a'
    else:
        open_cond = 'w'

    # Parse the basename for the mol header
    base_name = file.split(".")
    if len(base_name) > 1:
        base_name = ".".join(base_name[:-1])
    else:
        base_name = base_name[0]

    keep_lone = [count_i for count_i, i in enumerate(
        bond_mat) if i[count_i] % 2 == 1]

    # deal with radicals
    fc = list(return_formals(bond_mat, elements))

    # deal with charges
    chrg = len([i for i in fc if i != 0])
    valence = []  # count the number of bonds for mol file
    for count_i, i in enumerate(bond_mat):
        bond = 0
        for count_j, j in enumerate(i):
            if count_i != count_j:
                bond = bond+int(j)
        valence.append(bond)

    # Write the file
    with open(file, open_cond) as f:
        # Write the header
        f.write('{}\nGenerated by mol_write.py\n\n'.format(base_name))

        # Write the number of atoms and bonds
        f.write("{:>3d}{:>3d}  0  0  0  0  0  0  0  0  1 V2000\n".format(
            len(elements), int(np.sum(adj_mat/2.0))))

        # Write the geometry
        for count_i, i in enumerate(elements):
            f.write(" {:> 9.4f} {:> 9.4f} {:> 9.4f} {:<3s} 0 {:>2d}  0  0  0  {:>2d}  0  0  0  0  0  0\n".format(
                geo[count_i][0], geo[count_i][1], geo[count_i][2], i.capitalize(), mol_dict[fc[count_i]], valence[count_i]))

        # Write the bonds
        bonds = [(count_i, count_j) for count_i, i in enumerate(adj_mat)
                 for count_j, j in enumerate(i) if j == 1 and count_j > count_i]
        for i in bonds:

            # Calculate bond order from the bond_mat
            bond_order = int(bond_mat[i[0], i[1]])

            # add fix of bond order for dative bonds around the transition metal
            bond_elements = [elements[i[0]], elements[i[1]]]

            # print(f"bond_elements: {bond_elements}", flush = True)
            # if (_ in el_metals for _ in bond_elements):# and (bond_order == 0):
            #    #print(f"FOUND METAL! bond_elements: {bond_elements}", flush = True)
            #    bond_order = 1

            if bond_order == 0:
                bond_order = 1
            f.write("{:>3d}{:>3d}{:>3d}  0  0  0  0\n".format(
                i[0]+1, i[1]+1, bond_order))

        # write radical info if exist
        if len(keep_lone) > 0:
            if len(keep_lone) == 1:
                f.write("M  RAD{:>3d}{:>4d}{:>4d}\n".format(
                    1, keep_lone[0]+1, 2))
            elif len(keep_lone) == 2:
                f.write("M  RAD{:>3d}{:>4d}{:>4d}{:>4d}{:>4d}\n".format(
                    2, keep_lone[0]+1, 2, keep_lone[1]+1, 2))
            else:
                print("Only support one/two radical containing compounds, "
                      "radical info will be skipped in the output mol file...")

        if chrg > 0:
            if chrg == 1:
                charge = [i for i in fc if i != 0][0]
                f.write("M  CHG{:>3d}{:>4d}{:>4d}\n".format(
                    1, fc.index(charge)+1, int(charge)))
            else:
                info = ""
                fc_counter = 0
                for count_c, charge in enumerate(fc):
                    if charge != 0:
                        if (fc_counter % 8 == 0):  # Only 8 items a line#
                            info += "M  CHG{:>3d}".format(
                                chrg - fc_counter if chrg - fc_counter <= 8 else 8)
                        info += '{:>4d}{:>4d}'.format(count_c+1, int(charge))
                        fc_counter += 1
                info += '\n'
                f.write(info)

        f.write("M  END\n$$$$\n")

    return
