name: Python application test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version
        
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        
    - name: Initialize Conda
      shell: bash
      run: |
        conda init bash
        
    - name: Create Conda environment
      shell: bash
      run: |
        source ~/.bashrc
        conda env create --name classy_yarp --file env_linux.yaml
        
    - name: Activate Conda environment
      shell: bash
      run: |
        source ~/.bashrc
        conda activate classy_yarp
        conda info --envs
        conda list
        # Prepare pysis env
        cp .pysisyphusrc /home/runner/.pysisyphusrc
        ENV_PATH=/usr/share/miniconda/envs/classy_yarp/
        sed -i "s|CONDA_ENV|${ENV_PATH}|g" /home/runner/.pysisyphusrc
        pip install pytest 
        pip install . # install YARP
    - name: Run pytest
      run: |              
         source ~/.bashrc
         conda activate classy_yarp
         echo $CONDA_PREFIX
         echo $CONDA
         #/usr/share/miniconda/envs/classy_yarp/bin/xtb
         #which xtb
         home=$(pwd)
         cd $home/examples/
         pytest -s
         
         # test run main_xtb
         cd $home/pyTEST_Example/
         # xtb and crest are in conda bin, others in pip bin
         ENV_PATH=/usr/share/miniconda/envs/classy_yarp/
         sed -i "s|CONDA_PATH|${ENV_PATH}|g" test_rxn.py
         pytest -s
      shell: bash
